linters:
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck
  disable:
    - gosimple #deprecated https://github.com/golangci/golangci-lint/issues/357
    - unused #deprecated https://github.com/dominikh/go-tools/tree/master/cmd/unused
  fast: false

issues:
  # golangci-lint excludes by default some checks they consider "annoying"
  # A better practice is for each repo to choose which ones to disable
  exclude-use-default: false
  fix: true

run:
  modules-download-mode: readonly
