---
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
    main: ./cmd/
repository:
  - description: "A tool that creates a virtual MFA device and rotates access keys for a new AWS user."
    tap:
      owner: trussworks
      name: homebrew-tap
    homepage: "https://github.com/trussworks/setup-new-aws-user"
    commit_author:
      name: trussworks-infra
      email: infra+github@truss.works
archives:
  - id: foo
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
