before:
  hooks:
    - go mod download
builds:
- goos:
    - darwin
    - linux
  goarch:
    - amd64
  main: ./cmd/main.go
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
