before:
  hooks:
    - go mod download
builds:
- goos:
    - darwin
    - linux
  goarch:
    - amd64
  main: ./cmd/main.go
brews:
  - description: "A tool that creates a virtual MFA device and rotates access keys for a new AWS user."
    github:
      owner: trussworks
      name: homebrew-tap
    homepage: "https://github.com/trussworks/setup-new-aws-user"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
