env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- goos:
    - darwin
    - linux
  goarch:
    - amd64
  main: ./cmd/
brews:
  - description: "A tool that creates a virtual MFA device and rotates access keys for a new AWS user."
    github:
      owner: trussworks
      name: homebrew-tap
    homepage: "https://github.com/trussworks/setup-new-aws-user"
    commit_author:
      name: trussworks-infra
      email: infra+github@truss.works
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
