---
default: true
line_length:
  line_length: true
  code_blocks: false
no-duplicate-header:
  siblings_only: true
commands-show-output: false
fenced-code-language: false
code-block-style:
  style: consistent
