version: 2.1

orbs:
  tools: gotest/tools@0.0.13

jobs:
  validate:
    docker:
      - image: trussworks/circleci-docker-primary:735a60a78114453f050c2ba45400c4aa6c9e06f2
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
  test:
    macos:
      xcode: '11.3.0'
    steps:
      - checkout
      - go/mod-download:
          prefix: v1-mac
          path: /Users/distiller/go/pkg/mod
      - run:
          name: Install GoLang devtools
          command: ./do install-devtools

  release:
    docker:
      - image: goreleaser/goreleaser:v0.128
    steps:
      - checkout
      - run:
          name: Run goreleaser
          command: goreleaser

workflows:
  version: 2.1
  test:
    jobs:
      - validate
      - test
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /^.*/
            tags:
              only: /^v.*/
