jobs:
  test:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: trussworks/circleci:56e6e6ef96436eff868243a7a0e42322c4df43c5
    steps:
    - checkout
    - restore_cache:
        keys:
        - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        - go-mod-sources-v1-{{ checksum "go.sum" }}
    - run:
        command: pre-commit run -a
        name: Run pre-commit
    - run:
        command: make test
        name: Run Go tests
    - save_cache:
        key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        paths:
        - ~/.cache/pre-commit
    - save_cache:
        key: go-mod-sources-v1-{{ checksum "go.sum" }}
        paths:
        - ~/go/pkg/mod
references:
  circleci: trussworks/circleci:56e6e6ef96436eff868243a7a0e42322c4df43c5
version: 2.1
workflows:
  test:
    jobs:
    - test:
        context:
        - org-global
  version: 2.1
