name: Tests

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: make test
        run: make test
